### ISSUE TITLE
Formula structure

### ISSUE THREAD

**Issue by ickc** [pandoc-extras/pandocpm#6]
Split off from #2, particularly [this post](https://github.com/pandoc-extras/pandocpm/issues/2#issuecomment-262313528):

Proposed structure

```bash
/packages/filters/myfilter.yaml
/packages/filters/anotherfilter.yaml
/packages/templates/sometemplate.yaml
/packages/csl/somecsl.yaml
/packages/style/somestyle.yaml
```

**Comment by ickc** [comment]
Comments:

- the root `packages/` folder seems unnecessary.
- we could potentially opt for a flat structure, like [homebrew-cask's](https://github.com/caskroom/homebrew-cask/tree/master/Casks).
	- For:
		- Since the info of the kind of package is in the formula
	- Against:
		- for our limited use, managing an extra folder hierarchy is simple
		- easier when browsing and editing by humans
-  If we forego an index file (see #7), we probably need to clone all formulae locally, say, to `$DATADIR/pandocpm`.

**Comment by sergiocorreia** [comment]
- Agree that the packages folder seems unnecesary
- There are some disadvantages with a flat structure. EG if I click on the link you mentioned, I get "Sorry, we had to truncate this directory to 1,000 files. 2,519 entries were omitted from the list.". On top of that, there are filesystem slowdowns related with having many files in the same folder.

**Comment by ickc** [comment]
So let's use the proposed structure minus the root `packages/` folder.
